gem 'cucumber'
require 'cucumber/rake/task'

namespace :cucumber do
  Cucumber::Rake::Task.new(:ok) do |t|
    t.cucumber_opts = "--format progress"
  end
end

desc "Run features"
task :default => :"cucumber:ok"

